"""
Generation and Analysis of Speckle Patterns.

Documentation and examples are at <https://pyspeckle2.readthedocs.io>

Speckle is generated by one pair of functions that take a numpy-style shape,
so the same call works in one, two, or three dimensions::

    pyspeckle.create_exponential(M, pix_per_speckle)              # 1D
    pyspeckle.create_exponential((M, M), pix_per_speckle)         # 2D
    pyspeckle.create_exponential((M, M, M), pix_per_speckle)      # 3D
    pyspeckle.create_unpolarized(shape, pix_per_speckle)

A sequence of speckle patterns that decorrelate as the pupil translates,
returned with the correlation coefficient and its closed-form prediction::

    pyspeckle.create_boiling_speckle(shape, pix_per_speckle)

An OCT B-scan whose contrast falls from 1 to 1/sqrt(2) with depth while the
mean irradiance decays, returned with the depth and contrast of each row::

    pyspeckle.create_oct_speckle(shape, pix_per_speckle)

Arguments that do not apply to the requested dimensionality are rejected:
`alpha` and `aperture` need two dimensions, `beta` needs three.

When the pupil is not one of the named shapes, pass it directly.  Two
separated openings, for example, give speckle crossed by interference
fringes::

    pyspeckle.create_from_aperture(aperture, shape)

Rough-surface phase screens for partially developed speckle are the zero-mean
case, measured in radians::

    pyspeckle.create_phase_screen(shape, sigma, cl)

Analysis.  Everything below takes the dimensionality from its argument, except
`slice_plot`, which needs a volume::

    pyspeckle.autocorrelation(x)
    pyspeckle.local_contrast(x, kernel)
    pyspeckle.local_contrast_plot(x, kernel)
    pyspeckle.statistics_plot(x)
    pyspeckle.slice_plot(data, x, y, z)

Correlated Gaussian fields, which are *not* speckle -- the name refers to the
autocorrelation, not the distribution of values.  `cl` is the lag at which the
autocorrelation falls to 1/e for both shapes::

    pyspeckle.create_correlated(shape, mean, stdev, cl, correlation)

Correlated random numbers, the Gaussian copula of Duncan & Kirkpatrick::

    pyspeckle.box_muller(mu, sigma, N)
    pyspeckle.zvalues(r, N)
    pyspeckle.tvalues(r, N)
"""

__version__ = "0.6.1"
__author__ = "Scott Prahl"
__email__ = "scott.prahl@oit.edu"
__copyright__ = "2018-26, Scott Prahl"
__license__ = "MIT"
__url__ = "https://github.com/scottprahl/pyspeckle"

from .core import *
from .noise import *
from .plots import *
