"""
Analysis of two-dimensional speckle patterns.

Images are generated by `create_exponential` in `core`, which masks a uniform
random-phase field with an aperture and transforms it.  What remains here is
specific to two dimensions: contrast over a sliding window and the statistics
plots.

see Duncan & Kirkpatrick, "Algorithms for simulation of speckle," in SPIE
Vol. 6855 (2008)
"""

import numpy as np
import matplotlib.pyplot as plt

from .core import _sqrt_matrix, local_contrast

__all__ = (
    "local_contrast_2D_plot",
    "statistics_plot_2D",
)


def local_contrast_2D_plot(x, kernel):
    """
    Create a graph showing local and global spatial contrast.

    The kernel is an N x N array that describes the region over which
    contrast should be calculated.  For example, `np.ones((5,5))` would
    represent a 5x5 square.

    Args:
        x:       speckle pattern for which contrast is to be calculated
        kernel:  small region over which contrast is to be calculated

    Returns:
        nothing
    """
    C, K = local_contrast(x, kernel)

    plt.subplots(2, 2, figsize=(14, 12))
    plt.subplot(221)

    plt.imshow(_sqrt_matrix(x), cmap="gray")
    plt.xlabel("Position (pixels)")
    plt.ylabel("Position (pixels)")
    plt.title("Speckle Realization, Overall Contrast=%0.2f" % K)

    plt.subplot(222)
    # density=True scales the bins so that the PDF integrates to unity
    pdf, bins = np.histogram(x, bins=30, density=True)
    width = 0.7 * (bins[1] - bins[0])
    center = (bins[:-1] + bins[1:]) / 2
    plt.bar(center, pdf, align="center", width=width)
    plt.title("PDF of Speckle Realization")
    plt.xlabel("Gray level, g")
    plt.ylabel("PDF")

    plt.subplot(223)
    plt.imshow(_sqrt_matrix(C), cmap="gray")
    plt.xlabel("Position (pixels)")
    plt.ylabel("Position (pixels)")
    plt.title("Local speckle contrast")

    plt.subplot(224)
    pdf, bins = np.histogram(C, bins=20, density=True)
    width = 0.7 * (bins[1] - bins[0])
    center = (bins[:-1] + bins[1:]) / 2
    plt.bar(center, pdf, align="center", width=width)
    plt.title("PDF of Local Speckle Contrast")
    plt.xlabel("Local contrast, C")
    plt.ylabel("PDF")


def statistics_plot_2D(x, initialize=True):
    """
    Plot the first and second-order statistics of a speckle pattern.

    This routine calculates and plots the probability density function,
    PDF and the power spectral density, PSD.

    The PDF conforms to the formal definition that it integrate to unity.
    Also displayed is the contrast defined as the quotient of the standard
    deviation and the mean.

    Note that the PSD can be used to establish the dimensions of the
    minimum speckle size. When the display reaches the edge of the image,
    the speckle pattern (in that dimension) is at Nyquist, i.e., two
    pixels per (minimum) speckle. When the display occupies half of the
    image, the minimum speckle size is four pixels, etc. Of course this
    criterion applies separately in each dimension (horizontal and
    vertical); the speckle pattern need not be isotropic.

    Finally note that the display of the speckle pattern is the square
    root of its intensity. The square root operation has the effect of
    compressing the dynamic range of the pattern. A fully developed
    speckle pattern is of such high contrast (theoretically unity) that a
    display of the intensity itself does not reveal the nuance of the
    pattern.

    Args:
        x:       speckle pattern to be analyzed
        initialize: boolean to initialize the plot

    Returns:
        nothing
    """
    # with_extremes returns a new colormap, so the registered "gray" is untouched
    mymap = plt.get_cmap("gray").with_extremes(bad="blue")

    try:
        y = x.compressed()  # if masked array
    except AttributeError:
        y = x  # not a masked array

    ave = np.mean(y)
    std = np.std(y)

    if initialize:
        plt.subplots(2, 2, figsize=(14, 12))

    # Speckle Realization
    plt.subplot(2, 2, 1)
    plt.imshow(_sqrt_matrix(x), cmap=mymap)
    plt.title("Sqrt() of Speckle Irradiance")
    plt.xlabel("Position (pixels)")
    plt.ylabel("Position (pixels)")

    # Histogram of Probability Distribution Function
    plt.subplot(2, 2, 2)
    num_bins = 30
    #    plt.gca().set_aspect('equal')
    # density=True scales the bins so that the PDF integrates to unity
    pdf, bins = np.histogram(y, bins=num_bins, density=True)
    width = 0.7 * (bins[1] - bins[0])
    center = (bins[:-1] + bins[1:]) / 2
    plt.bar(center, pdf, align="center", width=width, color="gray")
    plt.xlabel("Irradiance (gray level/pixel)")
    plt.ylabel(r"Probability Distribution Function, $p_I(i)$")
    plt.title("Average = %.2f, Standard Deviation = %.2f" % (ave, std))

    # Power Spectral Density
    plt.subplot(2, 2, 3)
    plt.gca().set_aspect("equal")
    psd = np.fft.fftshift(np.fft.fft2(x))
    psd = 2 * np.log(abs(psd))
    plt.imshow(psd, cmap=mymap, extent=[-0.5, 0.5, -0.5, 0.5])
    plt.title("Log() of Power Spectral Density")
    plt.xlabel("Spatial Frequency (1/pixels)")
    plt.ylabel("Spatial Frequency (1/pixels)")

    # Probability Distribution Function on Log Scale
    plt.subplot(2, 2, 4)
    #    plt.gca().set_aspect('equal')
    plt.semilogy(center, pdf, "r.")
    plt.title("Speckle Contrast, K=%.3f" % (std / ave))
    plt.xlabel("Irradiance")
    plt.ylabel(r"Probability Distribution Function, $p_I(i)$")
