"""
Analysis of three-dimensional speckle patterns.

Volumes are generated by `create_exponential` in `core`, which builds them
from an ellipsoidal aperture.  What remains here is specific to three
dimensions: contrast over a sliding volume, and orthogonal slice plots.

see Duncan & Kirkpatrick, "Algorithms for simulation of speckle," in SPIE
Vol. 6855 (2008)
"""

import matplotlib.pyplot as plt

from .core import _sqrt_matrix

__all__ = ("slice_plot",)


def slice_plot(data, x, y, z, initialize=True, show_sqrt=True):
    """
    Plot the x, y, and z slices of 3D data cube.

    Args:
        data:       3D speckle pattern to be plotted
        x: constant x slice
        y: constant y slice
        z: constant z slice
        initialize: boolean to initialize plot
        show_sqrt: take sqrt() of image for better visualization

    Returns:
        nothing
    """
    # with_extremes returns a new colormap, so the registered "gray" is untouched
    mymap = plt.get_cmap("gray").with_extremes(bad="blue")

    if initialize:
        plt.subplots(2, 2, figsize=(9, 9))

    plt.subplot(2, 2, 1)
    plt.gca().set_aspect("equal")
    zz = data[:, :, z]
    if show_sqrt:
        zz = _sqrt_matrix(zz)
    plt.imshow(zz, cmap=mymap)
    plt.title("Constant Z=%d values" % z)
    plt.xlabel("X Position (pixels)")
    plt.ylabel("Y Position (pixels)")

    plt.subplot(2, 2, 2)
    plt.gca().set_aspect("equal")
    yy = data[:, y, :]
    if show_sqrt:
        yy = _sqrt_matrix(yy)
    plt.imshow(yy, cmap=mymap)
    plt.title("Constant Y=%d values" % y)
    plt.xlabel("X Position (pixels)")
    plt.ylabel("Z Position (pixels)")

    plt.subplot(2, 2, 3)
    plt.gca().set_aspect("equal")
    xx = data[x, :, :]
    if show_sqrt:
        xx = _sqrt_matrix(xx)
    plt.imshow(xx, cmap=mymap)
    plt.title("Constant X=%d values" % x)
    plt.xlabel("Y Position (pixels)")
    plt.ylabel("Z Position (pixels)")

    plt.subplot(2, 2, 4)
    plt.gca().axis("off")
